app/api/urls.py
from django.urls import path
from api.views.clients_view import ClientsView, TestView, ClientDetailView

urlpatterns = [
    path('clients/', ClientsView.as_view()),
    path("clients/<pk>", ClientDetailView.as_view()),
    path('test/', TestView.as_view()),
    
]

app/app/urls.py
from django.contrib import admin
from django.urls import path, include
from app.settings import MEDIA_ROOT, MEDIA_URL
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("signup/", include("signup.urls")),
    path("", include("web.urls")),
    path("api/", include("api.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
] + static(MEDIA_URL, document_root=MEDIA_ROOT)

app/web/urls.py
from django.urls import path

from web.views.index_view import IndexView
from web.views.cart_view import CartView
from web.views.comunication_view import ComunicationView
from web.views.comunication_interaction_view import ComunicationInteractionView
from web.views.checkout_view import CheckoutView
app_name = "web"

urlpatterns = [
    path('', IndexView.as_view(), name="index"),
    path('cart/', CartView.as_view(), name="cart"),
    path('comunication/', ComunicationView.as_view(), name="comunication"),
    path('comunication_interaction/', ComunicationInteractionView.as_view(), name="comunication_interaction"),
    path('checkout/', CheckoutView.as_view(), name="checkout" ),
]

app/cart/models.py
from django.db import models
from clients.models import ClientModel
from stock.models import StockModel
from django.db.models.signals import pre_save, post_delete
from django.dispatch import receiver
from stock.service import StockService
from django_q.tasks import async_task
from sales.services.cart_payout_service import PayoutService
# Create your models here.
class CartModel(models.Model):
    client = models.ForeignKey(ClientModel, on_delete=models.CASCADE)
    stock = models.ForeignKey(StockModel, on_delete=models.CASCADE)
    qt = models.FloatField()

    class Meta:
        unique_together = ("client", "stock")

@receiver(pre_save, sender=CartModel)
def hander_pre_save(sender, **kwargs):
    #comparar si hay la cantidad suficiente del producto selecionado
    if kwargs["instance"].stock.qt < kwargs["instance"].qt:
            #si no hay la cantidad suficiente lanza exception
            raise Exception("Stock insuficiente")
    if kwargs["instance"].pk:
        qt = kwargs["instance"].qt - CartModel.objects.get(pk=kwargs["instance"].pk).qt
    else:
        qt = kwargs["instance"].qt
    async_task(StockService.sock_managment_down, kwargs["instance"].stock, qt)

@receiver(post_delete, sender=CartModel)
def hander_post_delete(sender, **kwargs):
    PayoutService.post_payout(kwargs["instance"])

app/comunication/models.py
from django.db import models
from clients.models import ClientModel
# Create your models here.
class ComunicationModel(models.Model):
    client_question = models.ForeignKey(ClientModel, on_delete=models.DO_NOTHING, related_name="client_question")
    client_seller = models.ForeignKey(ClientModel,on_delete=models.CASCADE, related_name="client_seller")
    question = models.TextField()
    answer = models.TextField(blank=True, default="")

    @property
    def is_answer(self):
        return bool(self.answer)

app/web/forms/checkout_form.py
from django import forms
import datetime

now_year = int(str(datetime.datetime.now().year)[2:])

class CheckoutForm(forms.Form):
    card_number = forms.IntegerField(max_value=9507990000004905, min_value=1507990000004905)
    card_expiration_month= forms.IntegerField(max_value=12, min_value=1)
    card_expiration_year = forms.IntegerField(max_value=99, min_value=now_year)
    security_code = forms.IntegerField(max_value=999, min_value=0)
    card_holder_name = forms.CharField(max_length=128)
    card_holder_identification_type = forms.CharField(max_length=3, min_length=3,  initial="DNI")
    card_holder_identification_number = forms.IntegerField(max_value=99999999, min_value=10000)

app/cart/views.py
from django.shortcuts import render

# Create your views here.

app/comunication/views.py
from django.shortcuts import render

# Create your views here.

app/web/views/cart_view.py
from django.http import HttpResponse
from django.views import View
from django.template import loader
from django.contrib.auth.mixins import LoginRequiredMixin
from cart.models import CartModel
from stock.models import StockModel
from web.services.cart_service import CartService
from web.forms.checkout_form import CheckoutForm
class CartView(LoginRequiredMixin, View):
    def __init__(self, **kwargs) -> None:
        self.template = loader.get_template("web/cart.html")
        super().__init__(**kwargs)
    
    def get(self, request):
        context = CartService.get_context(request.user)
        if request.GET.get("route") == "checkout":
            self.template = loader.get_template("web/checkout.html")
            context["form"]= CheckoutForm
        
        return HttpResponse(self.template.render(context, request))
    
    def post(self, request):
        #traer stock del producto seleccionado
        stock = StockModel.objects.get(id=request.POST.get("id"))
        
        #trae el item del stock dentro del carro del cliente
        cart_model = CartModel.objects.filter(client=request.user, stock=stock).first()
        #si ya existe el item suma la qt 
        if cart_model:
            cart_model.qt += float(request.POST.get("qt"))
            cart_model.save()
        else:
        #sino crea el item para ese usuario    
            CartModel.objects.create(
                client=request.user, 
                stock=stock, 
                qt=float(request.POST.get("qt")))
        
        #traer el contexto desde un servico
        context = CartService.get_context(request.user)
        return HttpResponse(self.template.render(context, request))

app/web/views/checkout_view.py
import random
from django.http import HttpResponse
from django.views import View
from django.template import loader
from django.contrib.auth.mixins import LoginRequiredMixin
from web.forms.checkout_form import CheckoutForm
from sales.services.payment_service import PaymentService
from web.services.cart_service import CartService

class CheckoutView(LoginRequiredMixin, View):
    def __init__(self, **kwargs) -> None:
        self.template = loader.get_template("web/cart.html")
        super().__init__(**kwargs)
    
    def post(self, request):
        form = CheckoutForm(request.POST)
        
        if form.is_valid():
            result = PaymentService.generate_token(form)
            cart = CartService.get_context(request.user)
            payment = PaymentService.pay_transaction(cart.get("total"), str(random.randint(10000000, 999999999999999)), result.json()["id"])

        context = {
            "payment": payment
        }
        if payment:
            CartService.payout(request.user)
            
        template = loader.get_template("web/payment.html")
        
        return HttpResponse(template.render(context, request))

app/web/views/comunication_view.py
from django.http import HttpResponse
from django.views import View
from django.template import loader
from django.contrib.auth.mixins import LoginRequiredMixin
from stock.models import StockModel
from comunication.models import ComunicationModel
from clients.models import ClientModel
from django.shortcuts import redirect
from django.urls import reverse

class ComunicationView(LoginRequiredMixin, View):
    def __init__(self, **kwargs) -> None:
        self.template = loader.get_template("web/comunication.html")
        super().__init__(**kwargs)

    def get(self, request):
        stock = StockModel.objects.get(pk=request.GET.get("item"))

        context ={
            "seller": stock.client.pk,
            "initial_text" : f"Hola sr {stock.client.username} queria preguntar acerca del producto: {stock.name} (code:{stock.code}): "
        }
        return HttpResponse(self.template.render(context, request))
    
    def post(self, request):
        ComunicationModel.objects.create(
            client_question = ClientModel.objects.get(pk = int(request.POST.get("client"))),
            client_seller = ClientModel.objects.get(pk = int(request.POST.get("client_seller"))),
            question = request.POST.get("question")
        )
        return redirect(reverse("web:index"))

app/web/templates/web/cart.html
{% extends "base.html" %}

{% block content %}
{% load static %}

{% for item in cart %}
<p>{{item.stock.name}} - ${{item.stock.price}} - {{item.qt}}</p>
{% endfor %}
<p>Total a pagar:$ {{total}}</p>
<p>
    <a href="?route=checkout" class="btn btn-primary">Ir a pagar</a>
</p>
{% endblock content %}

app/web/templates/web/checkout.html
{% extends "base.html" %}

{% block content %}
{% load static %}
    <form action="{% url 'web:checkout' %}" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <p>
        <button type="submit" class="btn btn-primary">Pagar</button>
    </p>
</form>


{% endblock content %}

app/web/templates/web/comunication.html
{% extends "base.html" %}

{% block content %}
{% load static %}
<form method="post">
    {% csrf_token %}
    <input type="text" name="client_seller" hidden value="{{seller}}">
    <input type="text" name="client" hidden value="{{user.pk}}">
    <textarea name="question"  cols="30" rows="10">{{initial_text}}</textarea>
    <button type="submit">Enviar</button>
</form>
{% endblock content %}

app/web/templates/web/comunication_interaction.html
{% extends "base.html" %}

{% block content %}
{% load static %}
{% for c in comuncations %}
    {{c.question}} --> {{c.answer}} <br>
{% endfor %}
{% endblock content %}

app/web/templates/web/index.html
{% extends "base.html" %}

{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'index.css' %}" />


<br>
{% for s in stock %}
<form action="{% url 'web:cart' %}" method="POST">
    {% csrf_token %}
<p>
{% if s.image%}
<img src="{{s.image.url}}" alt="" srcset="" width="50" height="50">
{% else %}
<img src="{{images.default}}" alt="" srcset="" width="50" height="50">

{% endif %}

{{s.name}} -> {{s.client.username}}
${{s.price}}
<input type="text" value="{{s.pk}}" name="id" hidden>
<input type="number"  name="qt" >
<button type="submit">
    <img src="{{images.arrow}}" alt="" srcset="" width="40" height="20" style="transform:rotate(180deg);">
</button>

<a href="{% url 'web:comunication' %}?item={{s.pk}}">
    <img src="{{images.question}}" alt="" srcset="" width="30" height="15" >
</a>
</p>
</form>
 <br>
{% endfor %}

{% endblock content %}

app/web/templates/web/payment.html
{% extends "base.html" %}

{% block content %}
{% load static %}

{{payment}}
{% endblock content %}