app/api/urls.py
from django.urls import path
from api.views.clients_view import ClientsView, TestView, ClientDetailView

urlpatterns = [
    path('clients/', ClientsView.as_view()),
    path("clients/<pk>", ClientDetailView.as_view()),
    path('test/', TestView.as_view()),
    
]

app/app/urls.py
from django.contrib import admin
from django.urls import path, include
from app.settings import MEDIA_ROOT, MEDIA_URL
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("signup/", include("signup.urls")),
    path("", include("web.urls")),
    path("api/", include("api.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
] + static(MEDIA_URL, document_root=MEDIA_ROOT)

app/web/urls.py
from django.urls import path

from web.views.index_view import IndexView
from web.views.cart_view import CartView
from web.views.comunication_view import ComunicationView
from web.views.comunication_interaction_view import ComunicationInteractionView
from web.views.checkout_view import CheckoutView
app_name = "web"

urlpatterns = [
    path('', IndexView.as_view(), name="index"),
    path('cart/', CartView.as_view(), name="cart"),
    path('comunication/', ComunicationView.as_view(), name="comunication"),
    path('comunication_interaction/', ComunicationInteractionView.as_view(), name="comunication_interaction"),
    path('checkout/', CheckoutView.as_view(), name="checkout" ),
]

app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <title>Sellers</title>
</head>
<body>
    <div class="row" style="background-color: antiquewhite;">
        <div class="col">Hola {{user.email}} !</div>
        <div class="col"></div>
        <div class="col"></div>
        <div class="col">
            
            {% if user.is_authenticated %}
            <a href="{% url 'web:index' %}">Home</a>
            <a href="{% url 'web:cart' %}">Cart</a>
            <a href="{% url 'web:comunication_interaction' %}">Comunication</a>
            <a href="/accounts/logout">Salir</a>
            {% endif %}
        </div>
        

    </div>
    <div class="container">
    {% block content %}{% endblock content %}
</div>
</body>
</html>